angular.module('portfolioApp', ['ngSanitize'])
  .controller('PortfolioController', function() {

    var portfolio = this;

    var now = new Date();
    portfolio.currentYear = now.getFullYear();
    portfolio.timestamp = now.getTime();

    portfolio.projects = [
      {name: 'Kelly\'s Bootcamp App', type: 'Ionic Hybrid Mobile App', description:'<p>A hybrid mobile app for Kelly’s Bootcamp (http://kellysbootcamp.net/) to help bootcamp participants keep track of various statistics measured while working out. Built with Ionic Framework, AngularJS and PHP. It can be found on the iOS app store and the Google Play store under “Kellys Bootcamp”.</p>', preview: 'kbc_preview.png', images:['kbc_prs2.png','kbc_statdetails2.png','kbc_chart2.png','kbc_newstat2.png','kbc_account2.png']},
      {name: 'DirectSource', type: 'AngularJS Application', description:'<p>DirectSource was a product which helped connect CareerOneStop job center counselors with job seekers and employers through outreach. Built with AngularJS and PHP.</p>', preview: 'ds_joblisting2.png', images:['ds_joblisting2.png','ds_jobdetail2.png','ds_quickstart2.png','ds_topjobs2.png','ds_today2.png']},
      {name: 'Virtual Career Network', type: 'Drupal PHP Application', description: '<p>The Virtual Career Network (vcn.org) was an open source website that prepares users to get qualified for their desired career by obtaining educational qualifications and other required credentials.</p><p>Visit <a href=\'http://www.vcn.org\' target=\'_blank\'>Virtual Career Network</a></p>', preview: 'vcn_main2.png', images: ['vcn_main2.png','vcn_healthcare2.png','vcn_choosecareer2.png','vcn_getqualified2.png','vcn_findjob2.png']},
      {name: 'VeriTracks', type: 'VB.NET Web Application', description:'<p>VeriTracks was an VB.NET Web application with an Oracle and PL/SQL backend. It tracked over 10,000 paroled high risk sex offenders. The offenders wore a GPS ankle bracelet that took a GPS track point every minute and reported to our gateway servers over the cellular network every 10 minutes, which equated to over 4 billion track points a year.</p><p>I designed the front end which consisted of a widget based dashboard along with a large Google Map allowing the parole officers to quickly view the location of their offenders on a map while giving them the ability to look at tabular data to see if the offenders had any location or device violations.</p><p>This was a very rewarding product to work on due to the number of serious crimes the VeriTracks system helps to prevent.</p>', preview: 'vt_preview.png', images: ['vt_supervision.png','vt_monitoring.png','vt_enrollment.png']},
      {name: 'Internal Message Tracker', type: 'C# Web Application', description:'<p>The Internal Message Tracker (ITM) was used to keep track of feedback users submit about the Virtual Career Network (vcn.org) website. Users email their feedback and a windows service queries the exchange server to pull all emails and stores them in a SQL Server database.  VCN.org staff can then view the emails using the IMT website and assign them to the appropriate person, respond to the user and archive the message. The application was built using C# and ASP.NET with a SQL Server database and was modeled after Google\'s GMail application.</p>', preview: 'imt_preview.png', images: ['imt1.png', 'imt2.png']},
      {name: 'Flood Prediction Tool', type: 'PHP ArcIMS Application', description:'<p>NASA Langley Research Center (LaRC) is located in low level marsh land in southern Virginia and is susceptible to flooding during hurricane season. I was tasked by the NASA LaRC GIS Team to develop a web based mapping tool to help predict which buildings would possibly flood when water levels reach certain heights at nearby tidal stations. Using the GIS team\'s building elevation data along with a tidal feed from NOAA I was able to perform a simple calculation to roughly determine water levels for the entire center.</p><p>The application was built with ESRI\'s ArcIMS mapping server which interacted with an Oracle database to display the maps. I used PHP to build a customized API to communicate with ArcIMS in the backend and HTML/Javascript/CSS to build the front end.</p><p>The Flood Predication Tool is an internal application and is still used today by NASA LaRC facility managers.</p>', preview: 'ft_preview.png', images: ['floodtool1.png','floodtool2.png','floodtool3.png']},
      {name: 'Facility Disaster Estimator', type: 'PHP ArcIMS Application', description:'<p>NASA Langley Research Center (LaRC) contains multiple high pressure wind tunnels which could cause extensive damage to nearby buildings if one malfunctioned and then exploded. To determine which buildings are located in the danger zones, I created an application that estimates the blast radius depending on the type of pressure system. The application displays the LaRC basemap with various blast radius lines around a selected pressurized building and highlights all buildings that are inside of the blast radius. A report is also available detailing what materials the pressurized buildings and affected buildings contain.</p><p>The application was built with ESRI\'s ArcIMS mapping server along with PHP in the backend and HTML/Javascript/CSS in the front end.</p><p>The Facility Disaster Estimator is an internal application and is still used today by NASA LaRC facility managers.</p>', preview: 'pr_preview.png', images: ['pressure1.png','pressure2.png','pressure3.png']},
      {name: 'Children\'s Science Center', type: 'WordPress PHP Website', description:'<p>I was the volunteer webmaster for the Children\'s Science Center website for over 4 years. I kept the site updated with content from the board of directors and add new features when requested. The website was originally designed by another company and was created as a series of flat HTML files. I rebuilt the entire website within WordPress to be able to set up users that can modify content themselves as they please. The CSC website was updated with a new look and feel by another company in 2016.</p><p>Visit <a href=\'http://childsci.org/\' target=\'_blank\'>Children\'s Science Center</a></p>', preview: 'csc1.png', images: ['csc1.png']},
      {name: 'Boolean Girl', type: 'WordPress PHP Website', description:'<p>Boolean Girl was a website a friend of mine came up with that helps young girls learn computer programming, where girls can program with other girls. The idea is to get more girls in the field of computer science.</p><p>The look and feel of the site was already determined so I help move the static HTML pages into WordPress.</p>', preview: 'bg_2.png', images: ['bg_1.png','bg_2.png','bg_3.png']},
      {name: 'PHPArcIMSAPI', type: 'PHP API', description:'<p>The PHPArcIMSAPI came about while I was working with the NASA Langley Research Center\'s GIS Team. I was starting to develop the Flood Prediction Tool using ESRI\'s ArcIMS web mapping server and the requirement was to develop and host the application in a UNIX Sun environment. ArcIMS used custom APIs that ESRI built for Java, COM or ColdFusion and that was it. As a developer you would communicate with the web mapping server via ArcXML, ESRI\'s proprietary XML standard. The APIs would allow you to create objects and call specific methods which would send and receive the ArcXML.</p><p>I wanted to use PHP, my favorite development language, so I decided to build my own PHP version of ESRI\'s APIs. I knew what the ArcXML input needed to look like, as well as the ArcXML output coming from the web mapping server, so I just needed to build the PHP classes to handle it. Once I was done creating the key components of the API, I began building the Flood Prediction Tool, finishing the API along the way.</p><p>After several years of use, ESRI\'s ArcIMS product was replaced by a newer technology making the PHPArcIMSAPI obsolete. It is currently residing in GitHub for posterity.</p>', preview: null, images: []},
      {name: 'Softball Schedule', type: 'PHP Application', description:'<p>I built a simple PHP application so my softball team could view the current schedule and provide me, the coach at the time, a way to know who is going to make the game or not. As you may or may not know, getting adults to show up for intramural sports is a bit harder than getting eager and committed kids to show up for games, so at a minimum I wanted to know if I was going to have to find replacement players.</p><p>The application displayed all the games for the season in a simple grid with the next games at the very top in larger text. The games that were completed displayed the score while the games that hadn\'t been played yet allowed the user to see who is coming and set whether or not they were going to make the game.</p><p>We used this application for a few years until we decided to use a free sports team site called SportsVite.com.</p>', preview: null, images: []},
      {name: 'Contract Mgmt System', type: 'Classic ASP Application', description:'<p>Morgan Stanley processed thousands of contracts for customers and vendors each year. I joined this project as a developer to help create a contract management system for their entire global workforce. The system was designed to help organize all contracts by size, type, cost and importance. The system would track the contracts throughout their entire lifecycle, as well as allowing users to generate customized reports.</p><p>The application was built using classic ASP with a Sybase database and HTML/Javascript/CSS for the front end. I quickly became the project development lead when the original lead developer moved onto a different project.</p>', preview: null, images: []},
      {name: 'Career Directions', type: 'ArcIMS Application', description:'<p>The Delaware Department of Labor created a website that would allow job seekers to view information about employment opportunities and the labor market in general. Along with this information they wanted to be able to give their users the ability to look at a map to see what schools, child care centers and businesses are located near perspective job openings. Also, public transportation information was provided along with point to point directions allowing the user to determine their route to and from their home.</p><p>The site received the 2000 ESRI User Conference Special Achievement in GIS award.  This site is no longer available through the Delaware Department of Labor\'s website, but the following is a write up about the <a href=\'http://www.esri.com/news/arcnews/summer00articles/delawaredol.html\' target=\'_blank\'>Career Directions website</a> on ESRI\'s ArcNews Online magazine.</p>', preview: null, images: []},
      {name: 'Oil Pipeline Analysis Tool', type: 'ArcIMS Application', description:'<p>This application was built for a US government executive agency to help them determine the best location for an oil pipeline near the Caspian Sea. The client planned to take the information to help influence the parties involved. The client would be able to input numerous parameters into the application and be able to see the effects of those parameters on a map, helping them determine where the ideal place for the pipeline would be.</p><p>The application was built using ESRI\'s ArcView geographic information system software, along with it\'s Avenue programming language. I customized the entire application so that it no longer looked like the original ArcView front end, giving it it\'s own look and feel, which at the time was not a typical thing done with the software.</p><p>Unfortunately, I\'m not really sure what ever came of the oil pipeline or if the client was successful in using the tool to do their influencing.</p>', preview: null, images: []},
      {name: 'fbScour', type: 'PHP Application', description:'<p>fbScour is a website and service I built to help people find specific items they\'re interested in within Facebook yard sale groups by monitoring the group using keywords the user defines. When it finds items that match a keyword it saves the post and notifies the user.</p><p>Facebook yard sale groups are hot! Everyone loves a yard sale, so why not be the first one to call \'dibs\' on an item you are looking for? fbScour gives you a jump on the competition for acquiring the item you want by letting you know when it gets posted.</p><p>The website was built in PHP and MySQL with Twitter Bootstrap and jQuery for the front end.</p><p>This project has been discontinued.</p>', preview: null, images: []},
    ];

  });

